java.lang.NullPointerException
	at dm.util.MethodUtil.setMethod(Unknown Source)
	at dm.util.MethodUtil.<init>(Unknown Source)
	at dm.transformers.Transformers.transformClassForCodeSnippets(Unknown Source)
	at dm.CassandraTransformer.transformClass(Unknown Source)
	at dm.Transformer.transformClass(Unknown Source)
	at dm.Transformer.transform(Unknown Source)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at com.sun.management.OSMBeanFactory.getOperatingSystemMXBean(OSMBeanFactory.java:48)
	at sun.management.ManagementFactoryHelper.getOperatingSystemMXBean(ManagementFactoryHelper.java:105)
	at java.lang.management.PlatformComponent$7.getMXBeans(PlatformComponent.java:157)
	at java.lang.management.PlatformComponent.getMXBeans(PlatformComponent.java:376)
	at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:468)
	at sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:466)
	at sun.management.Agent.startAgent(Agent.java:260)
	at sun.management.Agent.startAgent(Agent.java:456)
javassist.NotFoundException: com.sun.jna.Native
	at javassist.ClassPool.get(ClassPool.java:452)
	at dm.util.ClassUtil.getClass(Unknown Source)
	at dm.util.ClassUtil.isTargetClass(Unknown Source)
	at dm.util.MethodUtil$2.edit(Unknown Source)
	at javassist.expr.ExprEditor.loopBody(ExprEditor.java:192)
	at javassist.expr.ExprEditor.doit(ExprEditor.java:91)
	at javassist.CtBehavior.instrument(CtBehavior.java:712)
	at dm.util.MethodUtil.insertCallInst(Unknown Source)
	at dm.CassandraTransformer.transformClassForHappensBefore(Unknown Source)
	at dm.CassandraTransformer.transformClass(Unknown Source)
	at dm.Transformer.transformClass(Unknown Source)
	at dm.Transformer.transform(Unknown Source)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:184)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:447)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:490)
java.lang.NullPointerException
	at dm.util.ClassUtil.isTargetClass(Unknown Source)
	at dm.util.MethodUtil$2.edit(Unknown Source)
	at javassist.expr.ExprEditor.loopBody(ExprEditor.java:192)
	at javassist.expr.ExprEditor.doit(ExprEditor.java:91)
	at javassist.CtBehavior.instrument(CtBehavior.java:712)
	at dm.util.MethodUtil.insertCallInst(Unknown Source)
	at dm.CassandraTransformer.transformClassForHappensBefore(Unknown Source)
	at dm.CassandraTransformer.transformClass(Unknown Source)
	at dm.Transformer.transformClass(Unknown Source)
	at dm.Transformer.transform(Unknown Source)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:184)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:447)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:490)
JX - WARN - 1&0 for org.apache.cassandra.service.StorageService.initClient()V
JX - WARN - 1&0 for org.apache.cassandra.locator.TokenMetadata.pendingRangeChanges(Ljava/net/InetAddress;)I
java.lang.NullPointerException
	at dm.util.MethodUtil.setMethod(Unknown Source)
	at dm.util.MethodUtil.<init>(Unknown Source)
	at dm.transformers.Transformers.transformClassForCodeSnippets(Unknown Source)
	at dm.CassandraTransformer.transformClass(Unknown Source)
	at dm.Transformer.transformClass(Unknown Source)
	at dm.Transformer.transform(Unknown Source)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.xerial.snappy.SnappyLoader.injectSnappyNativeLoader(SnappyLoader.java:283)
	at org.xerial.snappy.SnappyLoader.load(SnappyLoader.java:227)
	at org.xerial.snappy.Snappy.<clinit>(Snappy.java:48)
	at org.apache.cassandra.io.compress.SnappyCompressor.create(SnappyCompressor.java:45)
	at org.apache.cassandra.io.compress.SnappyCompressor.isAvailable(SnappyCompressor.java:55)
	at org.apache.cassandra.io.compress.SnappyCompressor.<clinit>(SnappyCompressor.java:37)
	at org.apache.cassandra.config.CFMetaData.<clinit>(CFMetaData.java:82)
	at org.apache.cassandra.config.KSMetaData.systemKeyspace(KSMetaData.java:81)
	at org.apache.cassandra.config.DatabaseDescriptor.loadYaml(DatabaseDescriptor.java:482)
	at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:126)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:216)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:447)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:490)
JX - WARN - 1&0 for org.apache.cassandra.db.DataTracker.removeUnreadableSSTables(Ljava/io/File;)V
JX - WARN - 2&1 for org.apache.cassandra.db.commitlog.CommitLogReplayer.recover(Ljava/io/File;)V
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
	at java.util.ArrayList$Itr.next(ArrayList.java:831)
	at javassist.compiler.MemberResolver.searchImports(MemberResolver.java:452)
	at javassist.compiler.MemberResolver.lookupClass(MemberResolver.java:412)
	at javassist.compiler.MemberResolver.lookupFieldByJvmName2(MemberResolver.java:274)
	at javassist.compiler.TypeChecker.fieldAccess2(TypeChecker.java:913)
	at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:870)
	at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:803)
	at javassist.compiler.TypeChecker.atExpr(TypeChecker.java:578)
	at javassist.compiler.ast.Expr.accept(Expr.java:68)
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:665)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:330)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.Javac.compileStmnt(Javac.java:569)
	at javassist.CtBehavior.insertBefore(CtBehavior.java:754)
	at javassist.CtBehavior.insertBefore(CtBehavior.java:734)
	at dm.util.MethodUtil.insertCallInstBefore(Unknown Source)
	at dm.CassandraTransformer.transformClassForHappensBefore(Unknown Source)
	at dm.CassandraTransformer.transformClass(Unknown Source)
	at dm.Transformer.transformClass(Unknown Source)
	at dm.Transformer.transform(Unknown Source)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.cassandra.db.commitlog.CommitLogAllocator.recycleSegment(CommitLogAllocator.java:193)
	at org.apache.cassandra.db.commitlog.CommitLog.recover(CommitLog.java:130)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:307)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:447)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:490)
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
	at java.util.ArrayList$Itr.next(ArrayList.java:831)
	at javassist.compiler.MemberResolver.searchImports(MemberResolver.java:452)
	at javassist.compiler.MemberResolver.lookupClass(MemberResolver.java:412)
	at javassist.compiler.MemberResolver.lookupFieldByJvmName2(MemberResolver.java:274)
	at javassist.compiler.TypeChecker.fieldAccess2(TypeChecker.java:913)
	at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:870)
	at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:803)
	at javassist.compiler.TypeChecker.atExpr(TypeChecker.java:578)
	at javassist.compiler.ast.Expr.accept(Expr.java:68)
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:665)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:330)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.Javac.compileStmnt(Javac.java:569)
	at javassist.CtBehavior.insertAfterAdvice(CtBehavior.java:892)
	at javassist.CtBehavior.insertAfter(CtBehavior.java:851)
	at javassist.CtBehavior.insertAfter(CtBehavior.java:792)
	at dm.util.MethodUtil.insertCallInstAfter(Unknown Source)
	at dm.CassandraTransformer.transformClassForHappensBefore(Unknown Source)
	at dm.CassandraTransformer.transformClass(Unknown Source)
	at dm.Transformer.transformClass(Unknown Source)
	at dm.Transformer.transform(Unknown Source)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.cassandra.db.commitlog.CommitLogAllocator.recycleSegment(CommitLogAllocator.java:193)
	at org.apache.cassandra.db.commitlog.CommitLog.recover(CommitLog.java:130)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:307)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:447)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:490)
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
	at java.util.ArrayList$Itr.next(ArrayList.java:831)
	at javassist.compiler.MemberResolver.searchImports(MemberResolver.java:452)
	at javassist.compiler.MemberResolver.lookupClass(MemberResolver.java:412)
	at javassist.compiler.MemberResolver.lookupFieldByJvmName2(MemberResolver.java:274)
	at javassist.compiler.TypeChecker.fieldAccess2(TypeChecker.java:913)
	at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:870)
	at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:803)
	at javassist.compiler.TypeChecker.atExpr(TypeChecker.java:578)
	at javassist.compiler.ast.Expr.accept(Expr.java:68)
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:665)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:330)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.Javac.compileStmnt(Javac.java:569)
	at javassist.CtBehavior.insertBefore(CtBehavior.java:754)
	at javassist.CtBehavior.insertBefore(CtBehavior.java:734)
	at dm.util.MethodUtil.insertCallInstBefore(Unknown Source)
	at dm.CassandraTransformer.transformClassForHappensBefore(Unknown Source)
	at dm.CassandraTransformer.transformClass(Unknown Source)
	at dm.Transformer.transformClass(Unknown Source)
	at dm.Transformer.transform(Unknown Source)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:326)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:447)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:490)
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
	at java.util.ArrayList$Itr.next(ArrayList.java:831)
	at javassist.compiler.MemberResolver.searchImports(MemberResolver.java:452)
	at javassist.compiler.MemberResolver.lookupClass(MemberResolver.java:412)
	at javassist.compiler.MemberResolver.lookupFieldByJvmName2(MemberResolver.java:274)
	at javassist.compiler.TypeChecker.fieldAccess2(TypeChecker.java:913)
	at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:870)
	at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:803)
	at javassist.compiler.TypeChecker.atExpr(TypeChecker.java:578)
	at javassist.compiler.ast.Expr.accept(Expr.java:68)
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:665)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:330)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.Javac.compileStmnt(Javac.java:569)
	at javassist.CtBehavior.insertAfterAdvice(CtBehavior.java:892)
	at javassist.CtBehavior.insertAfter(CtBehavior.java:851)
	at javassist.CtBehavior.insertAfter(CtBehavior.java:792)
	at dm.util.MethodUtil.insertCallInstAfter(Unknown Source)
	at dm.CassandraTransformer.transformClassForHappensBefore(Unknown Source)
	at dm.CassandraTransformer.transformClass(Unknown Source)
	at dm.Transformer.transformClass(Unknown Source)
	at dm.Transformer.transform(Unknown Source)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:326)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:447)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:490)
Killed
Command exited with non-zero status 137
real 150.14
user 84.54
sys 29.17
java.lang.NullPointerException
	at dm.util.MethodUtil.setMethod(Unknown Source)
	at dm.util.MethodUtil.<init>(Unknown Source)
	at dm.transformers.Transformers.transformClassForCodeSnippets(Unknown Source)
	at dm.CassandraTransformer.transformClass(Unknown Source)
	at dm.Transformer.transformClass(Unknown Source)
	at dm.Transformer.transform(Unknown Source)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at com.sun.management.OSMBeanFactory.getOperatingSystemMXBean(OSMBeanFactory.java:48)
	at sun.management.ManagementFactoryHelper.getOperatingSystemMXBean(ManagementFactoryHelper.java:105)
	at java.lang.management.PlatformComponent$7.getMXBeans(PlatformComponent.java:157)
	at java.lang.management.PlatformComponent.getMXBeans(PlatformComponent.java:376)
	at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:468)
	at sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:466)
	at sun.management.Agent.startAgent(Agent.java:260)
	at sun.management.Agent.startAgent(Agent.java:456)
javassist.NotFoundException: com.sun.jna.Native
	at javassist.ClassPool.get(ClassPool.java:452)
	at dm.util.ClassUtil.getClass(Unknown Source)
	at dm.util.ClassUtil.isTargetClass(Unknown Source)
	at dm.util.MethodUtil$2.edit(Unknown Source)
	at javassist.expr.ExprEditor.loopBody(ExprEditor.java:192)
	at javassist.expr.ExprEditor.doit(ExprEditor.java:91)
	at javassist.CtBehavior.instrument(CtBehavior.java:712)
	at dm.util.MethodUtil.insertCallInst(Unknown Source)
	at dm.CassandraTransformer.transformClassForHappensBefore(Unknown Source)
	at dm.CassandraTransformer.transformClass(Unknown Source)
	at dm.Transformer.transformClass(Unknown Source)
	at dm.Transformer.transform(Unknown Source)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:184)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:447)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:490)
java.lang.NullPointerException
	at dm.util.ClassUtil.isTargetClass(Unknown Source)
	at dm.util.MethodUtil$2.edit(Unknown Source)
	at javassist.expr.ExprEditor.loopBody(ExprEditor.java:192)
	at javassist.expr.ExprEditor.doit(ExprEditor.java:91)
	at javassist.CtBehavior.instrument(CtBehavior.java:712)
	at dm.util.MethodUtil.insertCallInst(Unknown Source)
	at dm.CassandraTransformer.transformClassForHappensBefore(Unknown Source)
	at dm.CassandraTransformer.transformClass(Unknown Source)
	at dm.Transformer.transformClass(Unknown Source)
	at dm.Transformer.transform(Unknown Source)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:184)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:447)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:490)
JX - WARN - 1&0 for org.apache.cassandra.service.StorageService.initClient()V
JX - WARN - 1&0 for org.apache.cassandra.locator.TokenMetadata.pendingRangeChanges(Ljava/net/InetAddress;)I
java.lang.NullPointerException
	at dm.util.MethodUtil.setMethod(Unknown Source)
	at dm.util.MethodUtil.<init>(Unknown Source)
	at dm.transformers.Transformers.transformClassForCodeSnippets(Unknown Source)
	at dm.CassandraTransformer.transformClass(Unknown Source)
	at dm.Transformer.transformClass(Unknown Source)
	at dm.Transformer.transform(Unknown Source)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.xerial.snappy.SnappyLoader.injectSnappyNativeLoader(SnappyLoader.java:283)
	at org.xerial.snappy.SnappyLoader.load(SnappyLoader.java:227)
	at org.xerial.snappy.Snappy.<clinit>(Snappy.java:48)
	at org.apache.cassandra.io.compress.SnappyCompressor.create(SnappyCompressor.java:45)
	at org.apache.cassandra.io.compress.SnappyCompressor.isAvailable(SnappyCompressor.java:55)
	at org.apache.cassandra.io.compress.SnappyCompressor.<clinit>(SnappyCompressor.java:37)
	at org.apache.cassandra.config.CFMetaData.<clinit>(CFMetaData.java:82)
	at org.apache.cassandra.config.KSMetaData.systemKeyspace(KSMetaData.java:81)
	at org.apache.cassandra.config.DatabaseDescriptor.loadYaml(DatabaseDescriptor.java:482)
	at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:126)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:216)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:447)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:490)
JX - WARN - 1&0 for org.apache.cassandra.db.DataTracker.removeUnreadableSSTables(Ljava/io/File;)V
JX - WARN - 2&1 for org.apache.cassandra.db.commitlog.CommitLogReplayer.recover(Ljava/io/File;)V
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
	at java.util.ArrayList$Itr.next(ArrayList.java:831)
	at javassist.compiler.MemberResolver.searchImports(MemberResolver.java:452)
	at javassist.compiler.MemberResolver.lookupClass(MemberResolver.java:412)
	at javassist.compiler.MemberResolver.lookupFieldByJvmName2(MemberResolver.java:274)
	at javassist.compiler.TypeChecker.fieldAccess2(TypeChecker.java:913)
	at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:870)
	at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:803)
	at javassist.compiler.TypeChecker.atExpr(TypeChecker.java:578)
	at javassist.compiler.ast.Expr.accept(Expr.java:68)
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:665)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:330)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.Javac.compileStmnt(Javac.java:569)
	at javassist.CtBehavior.insertBefore(CtBehavior.java:754)
	at javassist.CtBehavior.insertBefore(CtBehavior.java:734)
	at dm.util.MethodUtil.insertCallInstBefore(Unknown Source)
	at dm.CassandraTransformer.transformClassForHappensBefore(Unknown Source)
	at dm.CassandraTransformer.transformClass(Unknown Source)
	at dm.Transformer.transformClass(Unknown Source)
	at dm.Transformer.transform(Unknown Source)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.cassandra.db.commitlog.CommitLogAllocator.recycleSegment(CommitLogAllocator.java:193)
	at org.apache.cassandra.db.commitlog.CommitLog.recover(CommitLog.java:130)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:307)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:447)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:490)
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
	at java.util.ArrayList$Itr.next(ArrayList.java:831)
	at javassist.compiler.MemberResolver.searchImports(MemberResolver.java:452)
	at javassist.compiler.MemberResolver.lookupClass(MemberResolver.java:412)
	at javassist.compiler.MemberResolver.lookupFieldByJvmName2(MemberResolver.java:274)
	at javassist.compiler.TypeChecker.fieldAccess2(TypeChecker.java:913)
	at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:870)
	at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:803)
	at javassist.compiler.TypeChecker.atExpr(TypeChecker.java:578)
	at javassist.compiler.ast.Expr.accept(Expr.java:68)
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:665)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:330)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.Javac.compileStmnt(Javac.java:569)
	at javassist.CtBehavior.insertAfterAdvice(CtBehavior.java:892)
	at javassist.CtBehavior.insertAfter(CtBehavior.java:851)
	at javassist.CtBehavior.insertAfter(CtBehavior.java:792)
	at dm.util.MethodUtil.insertCallInstAfter(Unknown Source)
	at dm.CassandraTransformer.transformClassForHappensBefore(Unknown Source)
	at dm.CassandraTransformer.transformClass(Unknown Source)
	at dm.Transformer.transformClass(Unknown Source)
	at dm.Transformer.transform(Unknown Source)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.cassandra.db.commitlog.CommitLogAllocator.recycleSegment(CommitLogAllocator.java:193)
	at org.apache.cassandra.db.commitlog.CommitLog.recover(CommitLog.java:130)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:307)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:447)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:490)
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
	at java.util.ArrayList$Itr.next(ArrayList.java:831)
	at javassist.compiler.MemberResolver.searchImports(MemberResolver.java:452)
	at javassist.compiler.MemberResolver.lookupClass(MemberResolver.java:412)
	at javassist.compiler.MemberResolver.lookupFieldByJvmName2(MemberResolver.java:274)
	at javassist.compiler.TypeChecker.fieldAccess2(TypeChecker.java:913)
	at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:870)
	at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:803)
	at javassist.compiler.TypeChecker.atExpr(TypeChecker.java:578)
	at javassist.compiler.ast.Expr.accept(Expr.java:68)
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:665)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:330)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.Javac.compileStmnt(Javac.java:569)
	at javassist.CtBehavior.insertBefore(CtBehavior.java:754)
	at javassist.CtBehavior.insertBefore(CtBehavior.java:734)
	at dm.util.MethodUtil.insertCallInstBefore(Unknown Source)
	at dm.CassandraTransformer.transformClassForHappensBefore(Unknown Source)
	at dm.CassandraTransformer.transformClass(Unknown Source)
	at dm.Transformer.transformClass(Unknown Source)
	at dm.Transformer.transform(Unknown Source)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:326)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:447)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:490)
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
	at java.util.ArrayList$Itr.next(ArrayList.java:831)
	at javassist.compiler.MemberResolver.searchImports(MemberResolver.java:452)
	at javassist.compiler.MemberResolver.lookupClass(MemberResolver.java:412)
	at javassist.compiler.MemberResolver.lookupFieldByJvmName2(MemberResolver.java:274)
	at javassist.compiler.TypeChecker.fieldAccess2(TypeChecker.java:913)
	at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:870)
	at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:803)
	at javassist.compiler.TypeChecker.atExpr(TypeChecker.java:578)
	at javassist.compiler.ast.Expr.accept(Expr.java:68)
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:665)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:330)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.Javac.compileStmnt(Javac.java:569)
	at javassist.CtBehavior.insertAfterAdvice(CtBehavior.java:892)
	at javassist.CtBehavior.insertAfter(CtBehavior.java:851)
	at javassist.CtBehavior.insertAfter(CtBehavior.java:792)
	at dm.util.MethodUtil.insertCallInstAfter(Unknown Source)
	at dm.CassandraTransformer.transformClassForHappensBefore(Unknown Source)
	at dm.CassandraTransformer.transformClass(Unknown Source)
	at dm.Transformer.transformClass(Unknown Source)
	at dm.Transformer.transform(Unknown Source)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:326)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:447)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:490)
Killed
Command exited with non-zero status 137
real 166.98
user 84.06
sys 29.70
Killed
Command exited with non-zero status 137
real 129.64
user 9.77
sys 6.03
Command exited with non-zero status 137
real 120.08
user 9.46
sys 5.82
