/home/vagrant/hadoop/install/hadoop-2.3.0/bin/hdfs: line 232: -javaagent:/home/vagrant/JXCascading-detector/build/lib/DM.jar=-s%/home/vagrant/hadoop/install/hadoop-2.3.0/share/hadoop/common:/home/vagrant/hadoop/install/hadoop-2.3.0/share/hadoop/hdfs: No such file or directory
java.lang.NullPointerException
	at dm.util.MethodUtil.setMethod(Unknown Source)
	at dm.util.MethodUtil.<init>(Unknown Source)
	at dm.transformers.Transformers.transformClassForCodeSnippets(Unknown Source)
	at dm.HDFSTransformer.transformClass(Unknown Source)
	at dm.Transformer.transformClass(Unknown Source)
	at dm.Transformer.transform(Unknown Source)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback.<init>(JniBasedUnixGroupsMappingWithFallback.java:37)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:129)
	at org.apache.hadoop.security.Groups.<init>(Groups.java:63)
	at org.apache.hadoop.security.Groups.getUserToGroupsMappingService(Groups.java:239)
	at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:255)
	at org.apache.hadoop.security.UserGroupInformation.ensureInitialized(UserGroupInformation.java:232)
	at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:718)
	at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:703)
	at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:605)
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:2473)
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:2465)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2331)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:369)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:168)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:353)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:296)
	at org.apache.hadoop.fs.shell.PathData.expandAsGlob(PathData.java:325)
	at org.apache.hadoop.fs.shell.CommandWithDestination.getRemoteDestination(CommandWithDestination.java:113)
	at org.apache.hadoop.fs.shell.CopyCommands$Put.processOptions(CopyCommands.java:199)
	at org.apache.hadoop.fs.shell.Command.run(Command.java:153)
	at org.apache.hadoop.fs.FsShell.run(FsShell.java:255)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at org.apache.hadoop.fs.FsShell.main(FsShell.java:308)
java.lang.NullPointerException
	at dm.util.MethodUtil.setMethod(Unknown Source)
	at dm.util.MethodUtil.<init>(Unknown Source)
	at dm.transformers.Transformers.transformClassForCodeSnippets(Unknown Source)
	at dm.HDFSTransformer.transformClass(Unknown Source)
	at dm.Transformer.transformClass(Unknown Source)
	at dm.Transformer.transform(Unknown Source)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback.<init>(JniBasedUnixGroupsMappingWithFallback.java:38)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:129)
	at org.apache.hadoop.security.Groups.<init>(Groups.java:63)
	at org.apache.hadoop.security.Groups.getUserToGroupsMappingService(Groups.java:239)
	at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:255)
	at org.apache.hadoop.security.UserGroupInformation.ensureInitialized(UserGroupInformation.java:232)
	at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:718)
	at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:703)
	at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:605)
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:2473)
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:2465)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2331)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:369)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:168)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:353)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:296)
	at org.apache.hadoop.fs.shell.PathData.expandAsGlob(PathData.java:325)
	at org.apache.hadoop.fs.shell.CommandWithDestination.getRemoteDestination(CommandWithDestination.java:113)
	at org.apache.hadoop.fs.shell.CopyCommands$Put.processOptions(CopyCommands.java:199)
	at org.apache.hadoop.fs.shell.Command.run(Command.java:153)
	at org.apache.hadoop.fs.FsShell.run(FsShell.java:255)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at org.apache.hadoop.fs.FsShell.main(FsShell.java:308)
java.lang.NullPointerException
	at dm.util.MethodUtil.setMethod(Unknown Source)
	at dm.util.MethodUtil.<init>(Unknown Source)
	at dm.transformers.Transformers.transformClassForCodeSnippets(Unknown Source)
	at dm.HDFSTransformer.transformClass(Unknown Source)
	at dm.Transformer.transformClass(Unknown Source)
	at dm.Transformer.transform(Unknown Source)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at com.sun.security.auth.module.UnixLoginModule.login(UnixLoginModule.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:762)
	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:203)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:690)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:687)
	at javax.security.auth.login.LoginContext.login(LoginContext.java:595)
	at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:726)
	at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:703)
	at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:605)
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:2473)
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:2465)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2331)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:369)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:168)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:353)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:296)
	at org.apache.hadoop.fs.shell.PathData.expandAsGlob(PathData.java:325)
	at org.apache.hadoop.fs.shell.CommandWithDestination.getRemoteDestination(CommandWithDestination.java:113)
	at org.apache.hadoop.fs.shell.CopyCommands$Put.processOptions(CopyCommands.java:199)
	at org.apache.hadoop.fs.shell.Command.run(Command.java:153)
	at org.apache.hadoop.fs.FsShell.run(FsShell.java:255)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at org.apache.hadoop.fs.FsShell.main(FsShell.java:308)
JX - WARN - 1&0 for org.apache.hadoop.fs.s3native.NativeS3FileSystem.delete(Lorg/apache/hadoop/fs/Path;Z)Z
JX - WARN - 2&0 for org.apache.hadoop.fs.s3native.NativeS3FileSystem.listStatus(Lorg/apache/hadoop/fs/Path;)[Lorg/apache/hadoop/fs/FileStatus;
JX - WARN - 1&0 for org.apache.hadoop.fs.s3native.NativeS3FileSystem.rename(Lorg/apache/hadoop/fs/Path;Lorg/apache/hadoop/fs/Path;)Z
JX - WARN - 2&1 for org.apache.hadoop.hdfs.DFSClient.getBlockStorageLocations(Ljava/util/List;)[Lorg/apache/hadoop/fs/BlockStorageLocation;
JX - WARN - 3&2 for org.apache.hadoop.hdfs.DFSUtil.bytes2byteArray([BIB)[[B
JX - WARN - 1&0 for org.apache.hadoop.hdfs.DFSUtil.resolveWebHdfsUri(Ljava/net/URI;Lorg/apache/hadoop/conf/Configuration;)[Ljava/net/InetSocketAddress;
real 130.35
user 44.37
sys 14.94
/home/vagrant/hadoop/install/hadoop-2.3.0/bin/hdfs: line 232: -javaagent:/home/vagrant/JXCascading-detector/build/lib/DM.jar=-s%/home/vagrant/hadoop/install/hadoop-2.3.0/share/hadoop/common:/home/vagrant/hadoop/install/hadoop-2.3.0/share/hadoop/hdfs: No such file or directory
java.lang.NullPointerException
	at dm.util.MethodUtil.setMethod(Unknown Source)
	at dm.util.MethodUtil.<init>(Unknown Source)
	at dm.transformers.Transformers.transformClassForCodeSnippets(Unknown Source)
	at dm.HDFSTransformer.transformClass(Unknown Source)
	at dm.Transformer.transformClass(Unknown Source)
	at dm.Transformer.transform(Unknown Source)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback.<init>(JniBasedUnixGroupsMappingWithFallback.java:37)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:129)
	at org.apache.hadoop.security.Groups.<init>(Groups.java:63)
	at org.apache.hadoop.security.Groups.getUserToGroupsMappingService(Groups.java:239)
	at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:255)
	at org.apache.hadoop.security.UserGroupInformation.ensureInitialized(UserGroupInformation.java:232)
	at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:718)
	at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:703)
	at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:605)
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:2473)
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:2465)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2331)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:369)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:168)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:353)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:296)
	at org.apache.hadoop.fs.shell.PathData.expandAsGlob(PathData.java:325)
	at org.apache.hadoop.fs.shell.CommandWithDestination.getRemoteDestination(CommandWithDestination.java:113)
	at org.apache.hadoop.fs.shell.CopyCommands$Put.processOptions(CopyCommands.java:199)
	at org.apache.hadoop.fs.shell.Command.run(Command.java:153)
	at org.apache.hadoop.fs.FsShell.run(FsShell.java:255)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at org.apache.hadoop.fs.FsShell.main(FsShell.java:308)
java.lang.NullPointerException
	at dm.util.MethodUtil.setMethod(Unknown Source)
	at dm.util.MethodUtil.<init>(Unknown Source)
	at dm.transformers.Transformers.transformClassForCodeSnippets(Unknown Source)
	at dm.HDFSTransformer.transformClass(Unknown Source)
	at dm.Transformer.transformClass(Unknown Source)
	at dm.Transformer.transform(Unknown Source)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback.<init>(JniBasedUnixGroupsMappingWithFallback.java:38)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:129)
	at org.apache.hadoop.security.Groups.<init>(Groups.java:63)
	at org.apache.hadoop.security.Groups.getUserToGroupsMappingService(Groups.java:239)
	at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:255)
	at org.apache.hadoop.security.UserGroupInformation.ensureInitialized(UserGroupInformation.java:232)
	at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:718)
	at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:703)
	at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:605)
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:2473)
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:2465)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2331)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:369)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:168)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:353)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:296)
	at org.apache.hadoop.fs.shell.PathData.expandAsGlob(PathData.java:325)
	at org.apache.hadoop.fs.shell.CommandWithDestination.getRemoteDestination(CommandWithDestination.java:113)
	at org.apache.hadoop.fs.shell.CopyCommands$Put.processOptions(CopyCommands.java:199)
	at org.apache.hadoop.fs.shell.Command.run(Command.java:153)
	at org.apache.hadoop.fs.FsShell.run(FsShell.java:255)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at org.apache.hadoop.fs.FsShell.main(FsShell.java:308)
java.lang.NullPointerException
	at dm.util.MethodUtil.setMethod(Unknown Source)
	at dm.util.MethodUtil.<init>(Unknown Source)
	at dm.transformers.Transformers.transformClassForCodeSnippets(Unknown Source)
	at dm.HDFSTransformer.transformClass(Unknown Source)
	at dm.Transformer.transformClass(Unknown Source)
	at dm.Transformer.transform(Unknown Source)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at com.sun.security.auth.module.UnixLoginModule.login(UnixLoginModule.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:762)
	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:203)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:690)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:687)
	at javax.security.auth.login.LoginContext.login(LoginContext.java:595)
	at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:726)
	at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:703)
	at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:605)
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:2473)
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:2465)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2331)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:369)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:168)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:353)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:296)
	at org.apache.hadoop.fs.shell.PathData.expandAsGlob(PathData.java:325)
	at org.apache.hadoop.fs.shell.CommandWithDestination.getRemoteDestination(CommandWithDestination.java:113)
	at org.apache.hadoop.fs.shell.CopyCommands$Put.processOptions(CopyCommands.java:199)
	at org.apache.hadoop.fs.shell.Command.run(Command.java:153)
	at org.apache.hadoop.fs.FsShell.run(FsShell.java:255)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at org.apache.hadoop.fs.FsShell.main(FsShell.java:308)
JX - WARN - 1&0 for org.apache.hadoop.fs.s3native.NativeS3FileSystem.delete(Lorg/apache/hadoop/fs/Path;Z)Z
JX - WARN - 2&0 for org.apache.hadoop.fs.s3native.NativeS3FileSystem.listStatus(Lorg/apache/hadoop/fs/Path;)[Lorg/apache/hadoop/fs/FileStatus;
JX - WARN - 1&0 for org.apache.hadoop.fs.s3native.NativeS3FileSystem.rename(Lorg/apache/hadoop/fs/Path;Lorg/apache/hadoop/fs/Path;)Z
JX - WARN - 2&1 for org.apache.hadoop.hdfs.DFSClient.getBlockStorageLocations(Ljava/util/List;)[Lorg/apache/hadoop/fs/BlockStorageLocation;
JX - WARN - 3&2 for org.apache.hadoop.hdfs.DFSUtil.bytes2byteArray([BIB)[[B
JX - WARN - 1&0 for org.apache.hadoop.hdfs.DFSUtil.resolveWebHdfsUri(Ljava/net/URI;Lorg/apache/hadoop/conf/Configuration;)[Ljava/net/InetSocketAddress;
real 132.35
user 45.13
sys 15.72
real 118.34
user 27.18
sys 11.21
real 118.26
user 26.65
sys 10.39
